### ISSUE TITLE
2.3.00 Obj-C immediate crash after Launch

### ISSUE THREAD

**Issue by ABerkhout** [inbeacon/InbeaconSdk-IOS#4]
2.2.07 is working with same settings. Example project gives the same result.

Xcode 9.2
iOS 11.2

> dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/<UserName>/Library/Developer/CoreSimulator/Devices/1FD703B8-F7C6-49C6-A712-DE49ECF1DB94/data/Containers/Bundle/Application/85CD2D42-47D4-4D29-A7D0-7739CD112DAD/<AppName>.app/Frameworks/InbeaconSdk.framework/InbeaconSdk
  Reason: image not found

**Comment by ABerkhout** [comment]
Retry with Xcode 9.3 does work.

**Comment by rvwoens** [comment]
As stated in the docs: the 2.3 version is for Xcode 9.3, use 2.2.07 for XCode 9.2

Unfortunately, Apple Xcode libraries are completely incompatible between versions.
