### ISSUE TITLE
Incorrect errors for localized Info.plist strings

### ISSUE THREAD

**Issue by bart-kace** [inbeacon/InbeaconSdk-IOS#5]
Once the NSLocation*****Description is not defined in the Info.plist file, but localized in the InfoPlist.strings files the SDK throws an error.

SDK: ########## Error: NSLocationAlwaysUsageDescription not defined in plist
SDK: ########## NSLocationWhenInUseUsageDescription not defined in plist
SDK: ########## Error: NSLocationAlwaysAndWhenInUseUsageDescription not defined in plist

This is happening in SDK 2.3.01

**Comment by rvwoens** [comment]
You can ignore these errors for now. These are not fatal but just a reminder to the developer.
We will include a check for the localized strings.
