### ISSUE TITLE
ld: framework not found InbeaconSdk clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by MV-EricDeHaan** [inbeacon/InbeaconSdk-IOS#7]
I get above error when building my app. Last week all went well. But after this weekend with no changes (as far as I know) I get this error. Can someone help me with it?

**Comment by rvwoens** [comment]
normally this is because the framework is not embedded. Make sure its linked AND embedded.

**Comment by MV-EricDeHaan** [comment]
I have used it for sometime now (using Cocoapods) and it was working fine. But all of a sudden it does this. I tried removing the pod and reinstalling it. I thought that should make sure it is linked and embedded...

I added the pod line in another project (just to test) did a pod update and tried to build and got the same error! (I am using Xcode 9.4.1) What could be the issue?
